### ISSUE TITLE
selected patches

### ISSUE THREAD

**Issue by long123524** [Lewislou/Label-Effcient-Nuclei-Segmentation#1]
A very interesting work！ But I have a problem, Is the final selected patches used for the training 256*256 or 128*128? if it's 256*256, why do you want to perform secondary clustering?

**Comment by Lewislou** [comment]
> A very interesting work！ But I have a problem, Is the final selected patches used for the training 256_256 or 128_128? if it's 256*256, why do you want to perform secondary clustering?

Hi, thanks for your interest. We select patches of size 256. The secondary clustering in our CPS method is to calculate the intra-patch consistency and representativeness of each patch of size 256. You can check the second and third terms in the equation. (1) in our paper.
