### ISSUE TITLE
How to reproduce the instance segmentation results of Hover-net on the MoNuSeg dataset ?

### ISSUE THREAD

**Issue by windygoo** [Lewislou/Label-Effcient-Nuclei-Segmentation#2]
A great job !
From Table IV of your paper, I see that the AJI of Hover-net on the MoNuSeg dataset is 0.6602. I'm wondering how to reproduce this result. Could you give me some help? Thanks very much.

**Comment by Lewislou** [comment]
Hi, I reproduce Hover-net using this pytorch code repository: https://github.com/vqdang/hover_net.
Specifically, I use the 'original' mode with crop size [270,270] and out shape [80,80].

**Comment by windygooo** [comment]
Could the trained model weights be available? So that I can directly reproduce the test results without repetitive training.

**Comment by windygooo** [comment]
> Hi, I reproduce Hover-net using this pytorch code repository: https://github.com/vqdang/hover_net. Specifically, I use the 'original' mode with crop size [270,270] and out shape [80,80].


Thanks. Could the trained model weights be available? So that I can directly reproduce the test results without repetitive training.

**Comment by Lewislou** [comment]
> > Hi, I reproduce Hover-net using this pytorch code repository: https://github.com/vqdang/hover_net. Specifically, I use the 'original' mode with crop size [270,270] and out shape [80,80].
> 
> Thanks. Could the trained model weights be available? So that I can directly reproduce the test results without repetitive training.

Sorry, we did not keep the reproduced Hover-net checkpoints. If you need the checkpoints, I would recommend you to raise an issue on the Hover-net github page or email the authors of Hover-net.
